#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "armel"
name = "Armel"
description.en = "desc en"
description.fr = "desc fr"

version = "0.0.3~ynh1"

maintainers = ["zolkenn"]

[upstream]
license = "GPL-2.0-or-later"

[integration]
yunohost = ">= 12.1.33"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/armel"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]
    [resources.sources.main]
    url = "https://github.com/ArmelClo/armel/releases/download/3.0.0/armel"
    sha256 = "04a8b7f7c01b4d43900bd87c4c87b7d803df00d06b286b36c364b3d222e6e45f"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
